apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ml-server-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-server-frontend
    spec:
      containers:
      - name: ml-server-frontend
        image: index.docker.io/jdelfino/frontend:latest
        ports:
        - containerPort: 50051