apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-server-frontend
  name: ml-server-frontend
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: ml-server-frontend
  type: LoadBalancer