apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ml-server-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-server-backend
    spec:
      containers:
      - name: ml-server-backend
        image: index.docker.io/jdelfino/backend:latest
        ports:
        - containerPort: 50052