apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-server-backend
  name: ml-server-backend
spec:
  ports:
  - port: 50052
    protocol: TCP
    targetPort: 50052
    name: ml-server-backend
  selector:
    app: ml-server-backend
  type: LoadBalancer